#install some packages
# if(!require(labelled )) install.packages("labelled ")
if(!require(plotly)) install.packages("plotly")
if(!require(dplyr)) install.packages("dplyr")
if(!require(foreign)) install.packages("foreign")
if(!require(gdata)) install.packages("gdata")
if(!require(lubridate)) install.packages("lubridate")
if(!require(readxl)) install.packages("readxl")
if(!require(openxlsx)) install.packages("openxlsx")
if(!require(tidyr)) install.packages("tidyr")
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(textTools)) install.packages("textTools")
if (!require("pacman")) install.packages("pacman")
# if(!require(stringr)) install.packages("stringr")
# if(!require(stringi)) install.packages("stringi")
# if(!require(shinyalert)) install.packages("shinyalert")
# Load the package


# pacman::p_load_gh("trinker/textshape", "trinker/lexicon", "trinker/textclean")
# library(textTools)
library(dplyr)
library(DT)
library(foreign)
library(gdata)
library(haven)
library(lubridate)
library(openxlsx)
library(plotly)
library(readr)
library(readxl)
library(tidyverse)



# library(stringi)
# library(stringr)
# library(tidyr)
# library(fresh)
# library(leaflet)
# library(tidytext)
# library(tm)
# library(hcandersenr)
# library(shinyalert)
# library(bs4Dash)
# library(htmltools)
# library(pluralize)
# # library(shiny)
# library(shinyjs)
# library(SnowballC)
# library(splitstackshape)
# library(stopwords)
# library(susoapi)
# library(susoflows)
# library(readstata13)
# library(gdata)
# library(gtsummary)


# Stop word removal in R
# if(!require(SnowballC)) install.packages("SnowballC")
# if(!require(RTextTools)) install.packages("RTextTools")
# if(!require(hcandersenr)) install.packages("hcandersenr")
# if(!require(tidytext)) install.packages("tidytext")
# if(!require(stopwords)) install.packages("stopwords")
# if(!require(pluralize)) remotes::install_gitlab("hrbrmstr/pluralize")
# if(!require(gtsummary)) install.packages("gtsummary")
# if(!require(remotes)) install.packages("remotes")
# if(!require(devtools)) install.packages("devtools")
# if(!require(susoapi)) devtools::install_github("arthur-shaw/susoapi")
# if(!require(susoflows)) remotes::install_github("arthur-shaw/susoflows")
# if(!require(haven)) install.packages("haven")
# if(!require(dplyr)) install.packages("dplyr")
# if(!require(readstata13)) install.packages("readstata13")
# if(!require(foreign)) install.packages("foreign")
# if(!require(tidyr)) install.packages("tidyr")
# if(!require(splitstackshape)) install.packages("splitstackshape")
# if(!require(readr)) install.packages("readr")
# if(!require(readxl)) install.packages("readxl")
# if(!require(gdata)) install.packages("gdata")
# if(!require(openxlsx)) install.packages("openxlsx")
# if(!require(lubridate)) install.packages("lubridate")
# if(!require(stringi)) install.packages("stringi")
# if(!require(htmltools)) install.packages("htmltools")

#for latex 
# if(!require(tinytex)) tinytex::install_tinytex()
# library("tinytex")

# install.packages('RTextTools')
