#install some packages
# if(!require(labelled )) install.packages("labelled ")
if(!require(plotly)) install.packages("plotly")
if(!require(shinyalert)) install.packages("shinyalert")
if(!require(bslib)) install.packages("bslib")
if(!require(bsicons)) install.packages("bsicons")
# install.packages("bslib")
# Load the package

library(shinyalert)
library(bs4Dash)
library(dplyr)
library(DT)
library(foreign)
library(fresh)
library(gdata)
library(haven)
library(hcandersenr)
library(htmltools)
library(leaflet)
library(lubridate)
library(openxlsx)
library(plotly)
library(pluralize)
library(readr)
library(readxl)
library(shiny)
library(shinyjs)
library(tidyverse)
library(jsonlite)
# library(SnowballC)
# library(splitstackshape)
# library(stopwords)
library(stringi)
library(stringr)
library(susoapi)
library(susoflows)
library(tidyr)
library(tidytext)
library(tidyverse)
library(tm)

library(bslib)

# library(readstata13)
# library(gdata)
# library(gtsummary)


# Stop word removal in R
# if(!require(SnowballC)) install.packages("SnowballC")
# if(!require(RTextTools)) install.packages("RTextTools")
# if(!require(hcandersenr)) install.packages("hcandersenr")
# if(!require(tidytext)) install.packages("tidytext")
# if(!require(stopwords)) install.packages("stopwords")
# if(!require(pluralize)) remotes::install_gitlab("hrbrmstr/pluralize")
# if(!require(gtsummary)) install.packages("gtsummary")
# if(!require(remotes)) install.packages("remotes")
# if(!require(devtools)) install.packages("devtools")
# if(!require(susoapi)) devtools::install_github("arthur-shaw/susoapi")
# if(!require(susoflows)) remotes::install_github("arthur-shaw/susoflows")
# if(!require(haven)) install.packages("haven")
# if(!require(dplyr)) install.packages("dplyr")
# if(!require(readstata13)) install.packages("readstata13")
# if(!require(foreign)) install.packages("foreign")
# if(!require(tidyr)) install.packages("tidyr")
# if(!require(splitstackshape)) install.packages("splitstackshape")
# if(!require(readr)) install.packages("readr")
# if(!require(readxl)) install.packages("readxl")
# if(!require(gdata)) install.packages("gdata")
# if(!require(openxlsx)) install.packages("openxlsx")
# if(!require(lubridate)) install.packages("lubridate")
# if(!require(stringi)) install.packages("stringi")
# if(!require(htmltools)) install.packages("htmltools")

#for latex 
# if(!require(tinytex)) tinytex::install_tinytex()
# library("tinytex")

# install.packages('RTextTools')
